global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:9090']

  - job_name: 'invoice-service'
    static_configs:
      - targets: ['invoice-service:9092']

  - job_name: 'membership-service'
    static_configs:
      - targets: ['membership-service:9091'] 